### ISSUE TITLE
Todo list for kcp website and documentation

### ISSUE THREAD

**Issue by avinal** [kcp-dev/kcp.io#15]
## Todos

- [x] #19
- [ ] Update readme for build and contribution instructions 
- [ ] Port css/js for the homepage to hugo (check feasibility)
- [ ] Add CR examples

**Comment by avinal** [comment]
I think this issue is not relevant now. PTAL @sttts @clubanderson

**Comment by sttts** [comment]
Right, this predates the current website.
